### ISSUE TITLE
Telegram bot does not issue replies

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-reports-telegram-server#3]
- expected behavior: a message from the bot confirming receipt of report and a link to it on the map.
- current behavior: nothing.

**Comment by tomasholderness** [comment]
@matthewberryman unfortunately I can't debug locally as Telegram doesn't appear to allow multiple connections to the same bot end point.

At I guess I would say:
- either the database isn't issuing notifications, or,
- the bot can't connect to the db

**Comment by matthewberryman** [comment]
Oh, it's the wrong DB. fixing now

**Comment by matthewberryman** [comment]
Working.
